root: true
env:
  browser: true
  node: true
parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: latest
rules:
  no-undef: warn
  no-irregular-whitespace: warn