default:
  previousLabel: "<< previous"
  commentLabel: "[+ comment]"
  nextLabel: "next >>"
  comment: true
pages:
  landing:
    next: "/1"

  1:
    controlType: "color"
  2:
    controlType: "color"
  3:
    controlType: "color"
  4:
    controlType: "color"
  5:
    controlType: "slider-xy"
    xRange: "[0, 100]"
    yRange: "[0, 100]"
  6:
    controlType: "pcode"
  7:
    controlType: "slider"
  8:
    controlType: "color"
  9:
    controlType: "color"
  10:
    controlType: "color"
  11:
    controlType: "color"
  12:
    controlType: "color"
  13:
    controlType: "color"
    
